<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.yuku123</groupId>
        <artifactId>z-asset</artifactId>
        <version>1.0.1</version>
    </parent>
    <artifactId>z-asset-api</artifactId>
    <!-- 旧账：central 报缺 name，2026-10-08 补。 -->
    <name>z-asset-api</name>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-core</artifactId>
        </dependency>
    </dependencies>
</project>
